###

GET http://localhost:3000/api/products

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "Router", 
    "precio": 13,
    "marca": "Tp-link"
}

###

GET http://localhost:3000/api/products/3

###

POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "Mochila", 
    "precio": 33,
    "marca": "Hacendado"
}

###

PUT http://localhost:3000/api/products/3 HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "Pizarra", 
    "precio": 330,
    "marca": "Almor"
}

###
DELETE http://localhost:3000/api/users/1